### ISSUE TITLE
Same vocabulary should be used for input and output.

### ISSUE THREAD

**Issue by Natanande** [joniz7/rnn-chatbot#17]
Only generating one vocabulary and using it to tokenize both utterances and response data should fix it.

**Comment by joniz7** [comment]
https://github.com/joniz7/rnn-chatbot/commit/24f7a2b82929b0b11eb05c57438cfe79ff01e1ec

**Comment by Natanande** [comment]
Only fixed in decode!!!!

**Comment by joniz7** [comment]
https://github.com/joniz7/rnn-chatbot/commit/09a31a23ebd4a1efac4c828cb5b5290f12e0ea35
