### ISSUE TITLE
Check data. Model shouldn't generate stuff like "00" and things that are not from the dialogues.

### ISSUE THREAD

**Issue by Natanande** [joniz7/rnn-chatbot#35]

**Comment by Natanande** [comment]
things that needs to be pruned: 
all sentences that starts with a number or code (i.e. "a23").
all "cut to"
Remove lines that only contain names (these are caused by lines missing from original script or something)
etc.

**Comment by joniz7** [comment]
https://github.com/joniz7/rnn-chatbot/commit/8af31ca8785d2a140ac86cf2a574fc1d359f4b7b
